# Generated by Django 5.0.1 on 2026-05-02 22:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("nickname", models.CharField(blank=True, max_length=60)),
                (
                    "years_attended",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=6
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("6e", "6e"),
                                ("5e", "5e"),
                                ("4e", "4e"),
                                ("3e", "3e"),
                            ],
                            max_length=4,
                        ),
                        default=list,
                        size=4,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "country",
                    models.CharField(blank=True, default="Niger", max_length=80),
                ),
                ("profession", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cooptation_pending", "Cooptation en cours"),
                            ("awaiting_admin", "En attente de l'admin"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("purged", "Purgé"),
                        ],
                        default="cooptation_pending",
                        max_length=24,
                    ),
                ),
                (
                    "cooptation_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("all_accepted", "Deux accords"),
                            ("mixed", "Un accord, un refus"),
                            ("all_refused", "Deux refus"),
                            ("expired", "Expiré (J+14)"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("review_note", models.TextField(blank=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="cooptation__status_4c8b1b_idx"
                    ),
                    models.Index(fields=["email"], name="cooptation__email_17bd42_idx"),
                    models.Index(
                        fields=["retention_until"],
                        name="cooptation__retenti_367948_idx",
                    ),
                ],
            },
        ),
    ]
