# Generated by Django 5.0.1 on 2026-05-02 22:21

import cooptation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooptation", "0001_initial"),
        ("members", "0005_check_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="CooptationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=cooptation.models._make_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Accordée"),
                            ("refused", "Refusée"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooptation_requests",
                        to="cooptation.adminapplication",
                    ),
                ),
                (
                    "parrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooptation_requests",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at"],
                "indexes": [
                    models.Index(fields=["token"], name="cooptation__token_e8684b_idx"),
                    models.Index(
                        fields=["application", "response"],
                        name="cooptation__applica_9087f5_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "response"],
                        name="cooptation__expires_1e8ca9_idx",
                    ),
                ],
            },
        ),
    ]
