# Generated by Django 5.0.1 on 2026-05-02 22:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooptation", "0002_cooptationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("closed", "Réponse courte"),
                            ("open", "Réponse libre"),
                        ],
                        max_length=8,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "answer_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        default=list,
                        help_text="Clés de réponse acceptées (insensibles aux accents et à la casse). Vide pour les questions ouvertes.",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_answer", models.TextField()),
                ("auto_grade", models.BooleanField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to="cooptation.adminapplication",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cooptation.knowledgequestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question__position"],
                "unique_together": {("application", "question")},
            },
        ),
    ]
