# Generated by Django 5.0.1 on 2026-05-02 23:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooptation", "0003_knowledgequestion_questionnaireresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminapplication",
            name="questionnaire_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="knowledgequestion",
            name="answer_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=80),
                blank=True,
                default=list,
                help_text="Clés de réponse acceptées (insensible à accents/casse).",
                size=None,
            ),
        ),
    ]
