# Generated by Django 5.0.14 on 2026-05-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooptation', '0004_adminapplication_questionnaire_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapplication',
            name='cooptation_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
