# Generated by Django 5.0.14 on 2026-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooptation', '0005_adminapplication_cooptation_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapplication',
            name='referrer',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
