# Generated by Django 5.0.14 on 2026-05-07 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooptation', '0007_alter_adminapplication_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, size=4),
        ),
    ]
