# Generated by Django 5.0.1 on 2026-05-04 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_public_id",
                    models.CharField(
                        help_text="Cloudinary public_id (auto-rempli par l'upload admin).",
                        max_length=200,
                    ),
                ),
                (
                    "caption",
                    models.TextField(help_text="Description visible aux membres."),
                ),
                (
                    "taken_at",
                    models.DateField(
                        blank=True,
                        help_text="Date approximative — laisser vide si inconnue.",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lieu (ex. : Birni, Niamey, Paris).",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("published", "Publiée")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memories_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("taken_at"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "-taken_at"],
                        name="memoires_me_status_c83390_idx",
                    )
                ],
            },
        ),
    ]
