# Generated by Django 5.0.1 on 2026-05-02 09:25

import django.contrib.postgres.fields
import django.db.models.deletion
import members.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("nickname", models.CharField(blank=True, max_length=60)),
                (
                    "years_attended",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=members.models.default_years,
                        size=6,
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("6e", "6e"),
                                ("5e", "5e"),
                                ("4e", "4e"),
                                ("3e", "3e"),
                            ],
                            max_length=4,
                        ),
                        default=members.models.default_classes,
                        size=4,
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                ("country", models.CharField(default="Niger", max_length=80)),
                ("profession", models.CharField(blank=True, max_length=120)),
                ("photo_public_id", models.CharField(blank=True, max_length=200)),
                ("show_email", models.BooleanField(default=True)),
                ("show_whatsapp", models.BooleanField(default=True)),
                ("show_city", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("deleted", "Supprimé"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="members_mem_status_734de0_idx"
                    ),
                    models.Index(fields=["city"], name="members_mem_city_3f144e_idx"),
                    models.Index(
                        fields=["country"], name="members_mem_country_78350c_idx"
                    ),
                ],
            },
        ),
    ]
