# Generated by Django 5.0.1 on 2026-05-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest_weekly", models.BooleanField(default=False)),
                ("in_memoriam_alerts", models.BooleanField(default=True)),
                ("event_alerts", models.BooleanField(default=False)),
                ("tag_alerts", models.BooleanField(default=True)),
                ("data_saver", models.BooleanField(default=False)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
