# Generated by Django 5.0.1 on 2026-05-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_notificationpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charter_version", models.CharField(max_length=20)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "charter_version"],
                        name="members_con_member__e5d952_idx",
                    )
                ],
            },
        ),
    ]
