# Generated by Django 5.0.14 on 2026-05-03 12:15

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_check_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name_initial', models.CharField(max_length=10)),
                ('years_at_ceg', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6)),
                ('note', models.CharField(blank=True, help_text="Optionnel — courte ligne d'introduction visible publiquement.", max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removal_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, max_length=200)),
                ('added_by_admins', models.ManyToManyField(blank=True, related_name='ghost_entries_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name_initial', 'first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicsearchentry',
            constraint=models.CheckConstraint(check=models.Q(('last_name_initial__regex', '^[A-Za-zÀ-ÿ.]{1,2}$')), name='initial_must_be_one_or_two_chars'),
        ),
    ]
