# Generated by Django 5.0.14 on 2026-05-03 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_set_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ghost.entry.created', 'Fiche fantôme créée'), ('ghost.entry.signed_off', 'Cosignature ajoutée'), ('ghost.entry.signoff_removed', 'Cosignature retirée'), ('ghost.removal.requested', 'Demande de retrait soumise'), ('ghost.removal.confirmed', 'Demande de retrait confirmée'), ('ghost.removal.executed', 'Retrait exécuté'), ('ghost.removal.cancelled', 'Demande de retrait annulée par admin'), ('ghost.entry.purged', 'Fiche purgée')], max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for anonymous actions (e.g., a public removal request).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='members_aud_target__c7b9f6_idx'), models.Index(fields=['action', '-created_at'], name='members_aud_action_c8d4b9_idx')],
            },
        ),
    ]
