# Generated by Django 5.0.14 on 2026-05-03 17:57

import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsearchentry',
            name='removal_token',
            field=models.CharField(default=members.models._make_token, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('confirm_token', models.CharField(db_index=True, default=members.models._make_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_confirmation', 'En attente de confirmation'), ('confirmed', 'Confirmée — retrait exécuté'), ('expired', 'Expirée — non confirmée')], default='pending_confirmation', max_length=24)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to='members.publicsearchentry')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='members_rem_status_283a3a_idx')],
            },
        ),
    ]
