# Generated by Django 5.0.1 on 2026-05-04 10:32

import django.contrib.postgres.fields
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_alter_publicsearchentry_removal_token_removalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=4),
                default=members.models.default_classes,
                size=4,
            ),
        ),
    ]
