# Generated by Django 5.0.1 on 2026-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_alter_member_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ghost.entry.created", "Fiche fantôme créée"),
                    ("ghost.entry.signed_off", "Cosignature ajoutée"),
                    ("ghost.entry.signoff_removed", "Cosignature retirée"),
                    ("ghost.removal.requested", "Demande de retrait soumise"),
                    ("ghost.removal.confirmed", "Demande de retrait confirmée"),
                    ("ghost.removal.executed", "Retrait exécuté"),
                    ("ghost.removal.cancelled", "Demande de retrait annulée par admin"),
                    ("ghost.entry.purged", "Fiche purgée"),
                    ("memoriam.entry.published", "Fiche In Memoriam publiée"),
                    ("memoriam.entry.archived", "Fiche In Memoriam archivée"),
                    ("memoriam.nomination.created", "Nomination In Memoriam soumise"),
                ],
                max_length=64,
            ),
        ),
    ]
