# Generated by Django 5.0.14 on 2026-05-05 23:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_drop_classes_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsearchentry',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='publicsearchentry',
            name='last_name_initial',
            field=models.CharField(help_text="Une seule lettre, ou 2 lettres pour les préfixes type 'Mc' ou 'Da' (ex: 'M' pour Moussa). Pour préserver la confidentialité, on n'affiche jamais le nom complet sur la liste publique (master spec §6.5).", max_length=2, verbose_name='Initiale du nom (1 à 2 caractères)'),
        ),
        migrations.AlterField(
            model_name='publicsearchentry',
            name='years_at_ceg',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6, verbose_name='Années au CEG'),
        ),
    ]
