# Generated by Django 5.0.14 on 2026-05-07 14:01

import django.contrib.postgres.fields
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_publicsearchentry_initial_ux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=members.models.default_classes, size=4),
        ),
    ]
