# Generated by Django 5.0.14 on 2026-05-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auditlog_gestion_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
