# Generated by Django 5.0.14 on 2026-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_backfill_member_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ghost.entry.created', 'Fiche fantôme créée'), ('ghost.entry.signed_off', 'Cosignature ajoutée'), ('ghost.entry.signoff_removed', 'Cosignature retirée'), ('ghost.removal.requested', 'Demande de retrait soumise'), ('ghost.removal.confirmed', 'Demande de retrait confirmée'), ('ghost.removal.executed', 'Retrait exécuté'), ('ghost.removal.cancelled', 'Demande de retrait annulée par admin'), ('ghost.entry.purged', 'Fiche purgée'), ('memoriam.entry.published', 'Fiche In Memoriam publiée'), ('memoriam.entry.archived', 'Fiche In Memoriam archivée'), ('memoriam.nomination.created', 'Nomination In Memoriam soumise'), ('rgpd.member.purged', 'Membre purgé (RGPD)'), ('gestion.member.edited', 'Profil membre modifié (gestion)'), ('gestion.member.suspended', 'Compte suspendu (gestion)'), ('gestion.member.reactivated', 'Compte réactivé (gestion)'), ('gestion.member.username_changed', 'Identifiant WhatsApp modifié (gestion)'), ('gestion.login_link.reissued', 'Lien de connexion régénéré (gestion)'), ('gestion.application.approved', 'Candidature approuvée (gestion)'), ('gestion.application.rejected', 'Candidature rejetée (gestion)'), ('aide.query.no_results', 'Recherche aide sans résultat'), ('directory.query.no_results', 'Recherche annuaire sans résultat')], max_length=64),
        ),
    ]
