# Generated by Django 5.0.1 on 2026-07-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ghost.entry.created", "Fiche fantôme créée"),
                    ("ghost.entry.signed_off", "Cosignature ajoutée"),
                    ("ghost.entry.signoff_removed", "Cosignature retirée"),
                    ("ghost.removal.requested", "Demande de retrait soumise"),
                    ("ghost.removal.confirmed", "Demande de retrait confirmée"),
                    ("ghost.removal.executed", "Retrait exécuté"),
                    ("ghost.removal.cancelled", "Demande de retrait annulée par admin"),
                    ("ghost.entry.purged", "Fiche purgée"),
                    ("memoriam.entry.published", "Fiche In Memoriam publiée"),
                    ("memoriam.entry.archived", "Fiche In Memoriam archivée"),
                    ("memoriam.nomination.created", "Nomination In Memoriam soumise"),
                    ("rgpd.member.purged", "Membre purgé (RGPD)"),
                    ("gestion.member.edited", "Profil membre modifié (gestion)"),
                    ("gestion.member.suspended", "Compte suspendu (gestion)"),
                    ("gestion.member.reactivated", "Compte réactivé (gestion)"),
                    (
                        "gestion.member.username_changed",
                        "Identifiant WhatsApp modifié (gestion)",
                    ),
                    (
                        "gestion.login_link.reissued",
                        "Lien de connexion régénéré (gestion)",
                    ),
                    ("gestion.application.approved", "Candidature approuvée (gestion)"),
                    ("gestion.application.rejected", "Candidature rejetée (gestion)"),
                    ("aide.query.no_results", "Recherche aide sans résultat"),
                    ("directory.query.no_results", "Recherche annuaire sans résultat"),
                    ("memoires.memory.created", "Souvenir créé"),
                    ("memoires.memory.edited", "Souvenir modifié"),
                    ("memoires.memory.published", "Souvenir publié"),
                    ("memoires.memory.unpublished", "Souvenir dépublié"),
                    ("promotions.entry.claimed", "Fiche de classe revendiquée"),
                    (
                        "promotions.entry.unclaimed",
                        "Revendication de fiche de classe retirée",
                    ),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="ClassRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_year_start",
                    models.IntegerField(
                        help_text="1980 pour l'année scolaire 1980-1981.",
                        verbose_name="Année de rentrée",
                    ),
                ),
                ("class_label", models.CharField(max_length=4, verbose_name="Classe")),
                ("first_name", models.CharField(max_length=80, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=80, verbose_name="Nom"),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=60, verbose_name="Surnom"),
                ),
                (
                    "source_ref",
                    models.CharField(editable=False, max_length=60, unique=True),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Nom incomplet, ou personne listée deux fois dans les sources.",
                        verbose_name="À vérifier",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné quand le membre revendique cette fiche.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de classe",
                "verbose_name_plural": "Fiches de classe",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["school_year_start", "class_label"],
                        name="members_cla_school__91e6e5_idx",
                    )
                ],
            },
        ),
    ]
