# Generated by Django 5.0.1 on 2026-05-04 21:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InMemoriamEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("nickname", models.CharField(blank=True, max_length=80)),
                (
                    "years_attended",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=6,
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=8),
                        blank=True,
                        default=list,
                        size=8,
                    ),
                ),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("photo_public_id", models.CharField(blank=True, max_length=200)),
                ("tribute", models.TextField()),
                ("family_consent_giver", models.CharField(blank=True, max_length=200)),
                ("family_consent_date", models.DateField(blank=True, null=True)),
                (
                    "family_consent_canal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Téléphone"),
                            ("in_person", "En personne"),
                        ],
                        max_length=16,
                    ),
                ),
                ("approved_content_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publiée"),
                            ("archived", "Archivée"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memoriam_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche In Memoriam",
                "verbose_name_plural": "Fiches In Memoriam",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["status", "full_name"],
                        name="memoriam_in_status_a46b55_idx",
                    )
                ],
            },
        ),
    ]
